### ISSUE TITLE
Surface book 1 stylus not working in app

### ISSUE THREAD

**Issue by absurdist** [scrivanolabs/Scrivano#1]
I've found a strange thing,

my stylus works perfectly in paint,
and my mouse works in scrivano

buy my stylus wont draw in scrivano, I can select things but it won't draw 
until I click the laser pointer icon that makes the glowing lines,
then the stylus starts to work

cheers

good luck with the application

**Comment by scrivanolabs** [comment]
@absurdist Hi there, thank you for reporting this. Can you please share the Windows version that you're using and the model of the stylus that you're using? Also, it would be better if you'd raise your issue via email at scrivanolabs@gmail.com. This repository is not actively monitored and is not being used for tracking issues and support requests.

**Comment by absurdist** [comment]
Hello,

sorry I didn't follow up on this one, my surface book screen broke.
